//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN.ITEGAMAX._4._0.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class mainstrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mainstrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADMIN.ITEGAMAX._4._0.Resources.mainstrings", typeof(mainstrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnclose {
            get {
                return ResourceManager.GetString("btnclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understood.
        /// </summary>
        public static string btnunderstood {
            get {
                return ResourceManager.GetString("btnunderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITeGAMAX Admin.
        /// </summary>
        public static string comp_app_title {
            get {
                return ResourceManager.GetString("comp_app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITeGAMAX Admin.
        /// </summary>
        public static string comp_app_title2 {
            get {
                return ResourceManager.GetString("comp_app_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the language to.
        /// </summary>
        public static string strchangelangto {
            get {
                return ResourceManager.GetString("strchangelangto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string strcopyright {
            get {
                return ResourceManager.GetString("strcopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture affects how culture-dependent data (dates, currencies, numbers, and so on) is presented..
        /// </summary>
        public static string strculturemodalsettings {
            get {
                return ResourceManager.GetString("strculturemodalsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string strlangsettings {
            get {
                return ResourceManager.GetString("strlangsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ITeGAMAX Admin!.
        /// </summary>
        public static string strwelcome {
            get {
                return ResourceManager.GetString("strwelcome", resourceCulture);
            }
        }
    }
}
