//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITE.ITEGAMAX._4._0._2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class mainstrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mainstrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SITE.ITEGAMAX._4._0._2.Resources.mainstrings", typeof(mainstrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string straddress {
            get {
                return ResourceManager.GetString("straddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string strallrightsreserved {
            get {
                return ResourceManager.GetString("strallrightsreserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a member.
        /// </summary>
        public static string strbecomeamember {
            get {
                return ResourceManager.GetString("strbecomeamember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a partner.
        /// </summary>
        public static string strbecomeapartner {
            get {
                return ResourceManager.GetString("strbecomeapartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string strcallus {
            get {
                return ResourceManager.GetString("strcallus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the language to.
        /// </summary>
        public static string strchangelangto {
            get {
                return ResourceManager.GetString("strchangelangto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string strcontactinfo {
            get {
                return ResourceManager.GetString("strcontactinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string strcontactus {
            get {
                return ResourceManager.GetString("strcontactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string strcopyright {
            get {
                return ResourceManager.GetString("strcopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover more.
        /// </summary>
        public static string strdiscovermore {
            get {
                return ResourceManager.GetString("strdiscovermore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string stremail {
            get {
                return ResourceManager.GetString("stremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        public static string stremailus {
            get {
                return ResourceManager.GetString("stremailus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string strfollowus {
            get {
                return ResourceManager.GetString("strfollowus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string strholidays {
            get {
                return ResourceManager.GetString("strholidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Our Teams Works.
        /// </summary>
        public static string strhowourteamsworks {
            get {
                return ResourceManager.GetString("strhowourteamsworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITeGAMAX network.
        /// </summary>
        public static string stritegamaxnetwok {
            get {
                return ResourceManager.GetString("stritegamaxnetwok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job vacancies.
        /// </summary>
        public static string strjobvacancies {
            get {
                return ResourceManager.GetString("strjobvacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string strlangsettings {
            get {
                return ResourceManager.GetString("strlangsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Talk.
        /// </summary>
        public static string strletstalk {
            get {
                return ResourceManager.GetString("strletstalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are now looking for staff!.
        /// </summary>
        public static string strlookingforstaff {
            get {
                return ResourceManager.GetString("strlookingforstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address.
        /// </summary>
        public static string strofficeaddress {
            get {
                return ResourceManager.GetString("strofficeaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Time.
        /// </summary>
        public static string stropentime {
            get {
                return ResourceManager.GetString("stropentime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Address.
        /// </summary>
        public static string strouraddress {
            get {
                return ResourceManager.GetString("strouraddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string strourproducts {
            get {
                return ResourceManager.GetString("strourproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string strourservices {
            get {
                return ResourceManager.GetString("strourservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string strphone {
            get {
                return ResourceManager.GetString("strphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string strproducts {
            get {
                return ResourceManager.GetString("strproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string strquicklinks {
            get {
                return ResourceManager.GetString("strquicklinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Pages.
        /// </summary>
        public static string strrelatepages {
            get {
                return ResourceManager.GetString("strrelatepages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what we offer.
        /// </summary>
        public static string strseewhatweoffer {
            get {
                return ResourceManager.GetString("strseewhatweoffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string strservices {
            get {
                return ResourceManager.GetString("strservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        public static string strsitemap {
            get {
                return ResourceManager.GetString("strsitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spontaneous application.
        /// </summary>
        public static string strspontaneousapplication {
            get {
                return ResourceManager.GetString("strspontaneousapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of our website.
        /// </summary>
        public static string strthecontentofourwebsite {
            get {
                return ResourceManager.GetString("strthecontentofourwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays.
        /// </summary>
        public static string strweekdays {
            get {
                return ResourceManager.GetString("strweekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Choose Us.
        /// </summary>
        public static string strwhychooseus {
            get {
                return ResourceManager.GetString("strwhychooseus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Process.
        /// </summary>
        public static string strworkingprocess {
            get {
                return ResourceManager.GetString("strworkingprocess", resourceCulture);
            }
        }
    }
}
